//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.3074
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This code was auto-generated by Microsoft.Silverlight.ServiceReference, version 3.0.40624.0
// 
namespace AutoCompleteTest.AutoCompleteService {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="", ConfigurationName="AutoCompleteService.ProductAutoComplete")]
    public interface ProductAutoComplete {
        
        [System.ServiceModel.OperationContractAttribute(AsyncPattern=true, Action="urn:ProductAutoComplete/GetProductMatches", ReplyAction="urn:ProductAutoComplete/GetProductMatchesResponse")]
        System.IAsyncResult BeginGetProductMatches(string inputText, System.AsyncCallback callback, object asyncState);
        
        System.Collections.ObjectModel.ObservableCollection<string> EndGetProductMatches(System.IAsyncResult result);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    public interface ProductAutoCompleteChannel : AutoCompleteTest.AutoCompleteService.ProductAutoComplete, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    public partial class GetProductMatchesCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        public GetProductMatchesCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        public System.Collections.ObjectModel.ObservableCollection<string> Result {
            get {
                base.RaiseExceptionIfNecessary();
                return ((System.Collections.ObjectModel.ObservableCollection<string>)(this.results[0]));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    public partial class ProductAutoCompleteClient : System.ServiceModel.ClientBase<AutoCompleteTest.AutoCompleteService.ProductAutoComplete>, AutoCompleteTest.AutoCompleteService.ProductAutoComplete {
        
        private BeginOperationDelegate onBeginGetProductMatchesDelegate;
        
        private EndOperationDelegate onEndGetProductMatchesDelegate;
        
        private System.Threading.SendOrPostCallback onGetProductMatchesCompletedDelegate;
        
        private BeginOperationDelegate onBeginOpenDelegate;
        
        private EndOperationDelegate onEndOpenDelegate;
        
        private System.Threading.SendOrPostCallback onOpenCompletedDelegate;
        
        private BeginOperationDelegate onBeginCloseDelegate;
        
        private EndOperationDelegate onEndCloseDelegate;
        
        private System.Threading.SendOrPostCallback onCloseCompletedDelegate;
        
        public ProductAutoCompleteClient() {
        }
        
        public ProductAutoCompleteClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ProductAutoCompleteClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ProductAutoCompleteClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ProductAutoCompleteClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public System.Net.CookieContainer CookieContainer {
            get {
                System.ServiceModel.Channels.IHttpCookieContainerManager httpCookieContainerManager = this.InnerChannel.GetProperty<System.ServiceModel.Channels.IHttpCookieContainerManager>();
                if ((httpCookieContainerManager != null)) {
                    return httpCookieContainerManager.CookieContainer;
                }
                else {
                    return null;
                }
            }
            set {
                System.ServiceModel.Channels.IHttpCookieContainerManager httpCookieContainerManager = this.InnerChannel.GetProperty<System.ServiceModel.Channels.IHttpCookieContainerManager>();
                if ((httpCookieContainerManager != null)) {
                    httpCookieContainerManager.CookieContainer = value;
                }
                else {
                    throw new System.InvalidOperationException("Unable to set the CookieContainer. Please make sure the binding contains an HttpC" +
                            "ookieContainerBindingElement.");
                }
            }
        }
        
        public event System.EventHandler<GetProductMatchesCompletedEventArgs> GetProductMatchesCompleted;
        
        public event System.EventHandler<System.ComponentModel.AsyncCompletedEventArgs> OpenCompleted;
        
        public event System.EventHandler<System.ComponentModel.AsyncCompletedEventArgs> CloseCompleted;
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.IAsyncResult AutoCompleteTest.AutoCompleteService.ProductAutoComplete.BeginGetProductMatches(string inputText, System.AsyncCallback callback, object asyncState) {
            return base.Channel.BeginGetProductMatches(inputText, callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Collections.ObjectModel.ObservableCollection<string> AutoCompleteTest.AutoCompleteService.ProductAutoComplete.EndGetProductMatches(System.IAsyncResult result) {
            return base.Channel.EndGetProductMatches(result);
        }
        
        private System.IAsyncResult OnBeginGetProductMatches(object[] inValues, System.AsyncCallback callback, object asyncState) {
            string inputText = ((string)(inValues[0]));
            return ((AutoCompleteTest.AutoCompleteService.ProductAutoComplete)(this)).BeginGetProductMatches(inputText, callback, asyncState);
        }
        
        private object[] OnEndGetProductMatches(System.IAsyncResult result) {
            System.Collections.ObjectModel.ObservableCollection<string> retVal = ((AutoCompleteTest.AutoCompleteService.ProductAutoComplete)(this)).EndGetProductMatches(result);
            return new object[] {
                    retVal};
        }
        
        private void OnGetProductMatchesCompleted(object state) {
            if ((this.GetProductMatchesCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.GetProductMatchesCompleted(this, new GetProductMatchesCompletedEventArgs(e.Results, e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void GetProductMatchesAsync(string inputText) {
            this.GetProductMatchesAsync(inputText, null);
        }
        
        public void GetProductMatchesAsync(string inputText, object userState) {
            if ((this.onBeginGetProductMatchesDelegate == null)) {
                this.onBeginGetProductMatchesDelegate = new BeginOperationDelegate(this.OnBeginGetProductMatches);
            }
            if ((this.onEndGetProductMatchesDelegate == null)) {
                this.onEndGetProductMatchesDelegate = new EndOperationDelegate(this.OnEndGetProductMatches);
            }
            if ((this.onGetProductMatchesCompletedDelegate == null)) {
                this.onGetProductMatchesCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnGetProductMatchesCompleted);
            }
            base.InvokeAsync(this.onBeginGetProductMatchesDelegate, new object[] {
                        inputText}, this.onEndGetProductMatchesDelegate, this.onGetProductMatchesCompletedDelegate, userState);
        }
        
        private System.IAsyncResult OnBeginOpen(object[] inValues, System.AsyncCallback callback, object asyncState) {
            return ((System.ServiceModel.ICommunicationObject)(this)).BeginOpen(callback, asyncState);
        }
        
        private object[] OnEndOpen(System.IAsyncResult result) {
            ((System.ServiceModel.ICommunicationObject)(this)).EndOpen(result);
            return null;
        }
        
        private void OnOpenCompleted(object state) {
            if ((this.OpenCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.OpenCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void OpenAsync() {
            this.OpenAsync(null);
        }
        
        public void OpenAsync(object userState) {
            if ((this.onBeginOpenDelegate == null)) {
                this.onBeginOpenDelegate = new BeginOperationDelegate(this.OnBeginOpen);
            }
            if ((this.onEndOpenDelegate == null)) {
                this.onEndOpenDelegate = new EndOperationDelegate(this.OnEndOpen);
            }
            if ((this.onOpenCompletedDelegate == null)) {
                this.onOpenCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnOpenCompleted);
            }
            base.InvokeAsync(this.onBeginOpenDelegate, null, this.onEndOpenDelegate, this.onOpenCompletedDelegate, userState);
        }
        
        private System.IAsyncResult OnBeginClose(object[] inValues, System.AsyncCallback callback, object asyncState) {
            return ((System.ServiceModel.ICommunicationObject)(this)).BeginClose(callback, asyncState);
        }
        
        private object[] OnEndClose(System.IAsyncResult result) {
            ((System.ServiceModel.ICommunicationObject)(this)).EndClose(result);
            return null;
        }
        
        private void OnCloseCompleted(object state) {
            if ((this.CloseCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.CloseCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void CloseAsync() {
            this.CloseAsync(null);
        }
        
        public void CloseAsync(object userState) {
            if ((this.onBeginCloseDelegate == null)) {
                this.onBeginCloseDelegate = new BeginOperationDelegate(this.OnBeginClose);
            }
            if ((this.onEndCloseDelegate == null)) {
                this.onEndCloseDelegate = new EndOperationDelegate(this.OnEndClose);
            }
            if ((this.onCloseCompletedDelegate == null)) {
                this.onCloseCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnCloseCompleted);
            }
            base.InvokeAsync(this.onBeginCloseDelegate, null, this.onEndCloseDelegate, this.onCloseCompletedDelegate, userState);
        }
        
        protected override AutoCompleteTest.AutoCompleteService.ProductAutoComplete CreateChannel() {
            return new ProductAutoCompleteClientChannel(this);
        }
        
        private class ProductAutoCompleteClientChannel : ChannelBase<AutoCompleteTest.AutoCompleteService.ProductAutoComplete>, AutoCompleteTest.AutoCompleteService.ProductAutoComplete {
            
            public ProductAutoCompleteClientChannel(System.ServiceModel.ClientBase<AutoCompleteTest.AutoCompleteService.ProductAutoComplete> client) : 
                    base(client) {
            }
            
            public System.IAsyncResult BeginGetProductMatches(string inputText, System.AsyncCallback callback, object asyncState) {
                object[] _args = new object[1];
                _args[0] = inputText;
                System.IAsyncResult _result = base.BeginInvoke("GetProductMatches", _args, callback, asyncState);
                return _result;
            }
            
            public System.Collections.ObjectModel.ObservableCollection<string> EndGetProductMatches(System.IAsyncResult result) {
                object[] _args = new object[0];
                System.Collections.ObjectModel.ObservableCollection<string> _result = ((System.Collections.ObjectModel.ObservableCollection<string>)(base.EndInvoke("GetProductMatches", _args, result)));
                return _result;
            }
        }
    }
}
