//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.1
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This code was auto-generated by Microsoft.Silverlight.ServiceReference, version 4.0.50401.0
// 
namespace TypeSharingClient.Service {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="", ConfigurationName="Service.TestService")]
    public interface TestService {
        
        [System.ServiceModel.OperationContractAttribute(AsyncPattern=true, Action="urn:TestService/GetCustomer", ReplyAction="urn:TestService/GetCustomerResponse")]
        System.IAsyncResult BeginGetCustomer(int customerID, System.AsyncCallback callback, object asyncState);
        
        DataClasses.Customer EndGetCustomer(System.IAsyncResult result);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface TestServiceChannel : TypeSharingClient.Service.TestService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class GetCustomerCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        public GetCustomerCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        public DataClasses.Customer Result {
            get {
                base.RaiseExceptionIfNecessary();
                return ((DataClasses.Customer)(this.results[0]));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class TestServiceClient : System.ServiceModel.ClientBase<TypeSharingClient.Service.TestService>, TypeSharingClient.Service.TestService {
        
        private BeginOperationDelegate onBeginGetCustomerDelegate;
        
        private EndOperationDelegate onEndGetCustomerDelegate;
        
        private System.Threading.SendOrPostCallback onGetCustomerCompletedDelegate;
        
        private BeginOperationDelegate onBeginOpenDelegate;
        
        private EndOperationDelegate onEndOpenDelegate;
        
        private System.Threading.SendOrPostCallback onOpenCompletedDelegate;
        
        private BeginOperationDelegate onBeginCloseDelegate;
        
        private EndOperationDelegate onEndCloseDelegate;
        
        private System.Threading.SendOrPostCallback onCloseCompletedDelegate;
        
        public TestServiceClient() {
        }
        
        public TestServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public TestServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public TestServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public TestServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public System.Net.CookieContainer CookieContainer {
            get {
                System.ServiceModel.Channels.IHttpCookieContainerManager httpCookieContainerManager = this.InnerChannel.GetProperty<System.ServiceModel.Channels.IHttpCookieContainerManager>();
                if ((httpCookieContainerManager != null)) {
                    return httpCookieContainerManager.CookieContainer;
                }
                else {
                    return null;
                }
            }
            set {
                System.ServiceModel.Channels.IHttpCookieContainerManager httpCookieContainerManager = this.InnerChannel.GetProperty<System.ServiceModel.Channels.IHttpCookieContainerManager>();
                if ((httpCookieContainerManager != null)) {
                    httpCookieContainerManager.CookieContainer = value;
                }
                else {
                    throw new System.InvalidOperationException("Unable to set the CookieContainer. Please make sure the binding contains an HttpC" +
                            "ookieContainerBindingElement.");
                }
            }
        }
        
        public event System.EventHandler<GetCustomerCompletedEventArgs> GetCustomerCompleted;
        
        public event System.EventHandler<System.ComponentModel.AsyncCompletedEventArgs> OpenCompleted;
        
        public event System.EventHandler<System.ComponentModel.AsyncCompletedEventArgs> CloseCompleted;
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.IAsyncResult TypeSharingClient.Service.TestService.BeginGetCustomer(int customerID, System.AsyncCallback callback, object asyncState) {
            return base.Channel.BeginGetCustomer(customerID, callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        DataClasses.Customer TypeSharingClient.Service.TestService.EndGetCustomer(System.IAsyncResult result) {
            return base.Channel.EndGetCustomer(result);
        }
        
        private System.IAsyncResult OnBeginGetCustomer(object[] inValues, System.AsyncCallback callback, object asyncState) {
            int customerID = ((int)(inValues[0]));
            return ((TypeSharingClient.Service.TestService)(this)).BeginGetCustomer(customerID, callback, asyncState);
        }
        
        private object[] OnEndGetCustomer(System.IAsyncResult result) {
            DataClasses.Customer retVal = ((TypeSharingClient.Service.TestService)(this)).EndGetCustomer(result);
            return new object[] {
                    retVal};
        }
        
        private void OnGetCustomerCompleted(object state) {
            if ((this.GetCustomerCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.GetCustomerCompleted(this, new GetCustomerCompletedEventArgs(e.Results, e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void GetCustomerAsync(int customerID) {
            this.GetCustomerAsync(customerID, null);
        }
        
        public void GetCustomerAsync(int customerID, object userState) {
            if ((this.onBeginGetCustomerDelegate == null)) {
                this.onBeginGetCustomerDelegate = new BeginOperationDelegate(this.OnBeginGetCustomer);
            }
            if ((this.onEndGetCustomerDelegate == null)) {
                this.onEndGetCustomerDelegate = new EndOperationDelegate(this.OnEndGetCustomer);
            }
            if ((this.onGetCustomerCompletedDelegate == null)) {
                this.onGetCustomerCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnGetCustomerCompleted);
            }
            base.InvokeAsync(this.onBeginGetCustomerDelegate, new object[] {
                        customerID}, this.onEndGetCustomerDelegate, this.onGetCustomerCompletedDelegate, userState);
        }
        
        private System.IAsyncResult OnBeginOpen(object[] inValues, System.AsyncCallback callback, object asyncState) {
            return ((System.ServiceModel.ICommunicationObject)(this)).BeginOpen(callback, asyncState);
        }
        
        private object[] OnEndOpen(System.IAsyncResult result) {
            ((System.ServiceModel.ICommunicationObject)(this)).EndOpen(result);
            return null;
        }
        
        private void OnOpenCompleted(object state) {
            if ((this.OpenCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.OpenCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void OpenAsync() {
            this.OpenAsync(null);
        }
        
        public void OpenAsync(object userState) {
            if ((this.onBeginOpenDelegate == null)) {
                this.onBeginOpenDelegate = new BeginOperationDelegate(this.OnBeginOpen);
            }
            if ((this.onEndOpenDelegate == null)) {
                this.onEndOpenDelegate = new EndOperationDelegate(this.OnEndOpen);
            }
            if ((this.onOpenCompletedDelegate == null)) {
                this.onOpenCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnOpenCompleted);
            }
            base.InvokeAsync(this.onBeginOpenDelegate, null, this.onEndOpenDelegate, this.onOpenCompletedDelegate, userState);
        }
        
        private System.IAsyncResult OnBeginClose(object[] inValues, System.AsyncCallback callback, object asyncState) {
            return ((System.ServiceModel.ICommunicationObject)(this)).BeginClose(callback, asyncState);
        }
        
        private object[] OnEndClose(System.IAsyncResult result) {
            ((System.ServiceModel.ICommunicationObject)(this)).EndClose(result);
            return null;
        }
        
        private void OnCloseCompleted(object state) {
            if ((this.CloseCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.CloseCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void CloseAsync() {
            this.CloseAsync(null);
        }
        
        public void CloseAsync(object userState) {
            if ((this.onBeginCloseDelegate == null)) {
                this.onBeginCloseDelegate = new BeginOperationDelegate(this.OnBeginClose);
            }
            if ((this.onEndCloseDelegate == null)) {
                this.onEndCloseDelegate = new EndOperationDelegate(this.OnEndClose);
            }
            if ((this.onCloseCompletedDelegate == null)) {
                this.onCloseCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnCloseCompleted);
            }
            base.InvokeAsync(this.onBeginCloseDelegate, null, this.onEndCloseDelegate, this.onCloseCompletedDelegate, userState);
        }
        
        protected override TypeSharingClient.Service.TestService CreateChannel() {
            return new TestServiceClientChannel(this);
        }
        
        private class TestServiceClientChannel : ChannelBase<TypeSharingClient.Service.TestService>, TypeSharingClient.Service.TestService {
            
            public TestServiceClientChannel(System.ServiceModel.ClientBase<TypeSharingClient.Service.TestService> client) : 
                    base(client) {
            }
            
            public System.IAsyncResult BeginGetCustomer(int customerID, System.AsyncCallback callback, object asyncState) {
                object[] _args = new object[1];
                _args[0] = customerID;
                System.IAsyncResult _result = base.BeginInvoke("GetCustomer", _args, callback, asyncState);
                return _result;
            }
            
            public DataClasses.Customer EndGetCustomer(System.IAsyncResult result) {
                object[] _args = new object[0];
                DataClasses.Customer _result = ((DataClasses.Customer)(base.EndInvoke("GetCustomer", _args, result)));
                return _result;
            }
        }
    }
}
